name: loadable_buttons
description: "Provides enhanced buttons with built-in loading states, async functionality and customizable transitions."
version: 0.1.0+1
homepage: https://hectoraguero.dev/
repository: https://github.com/hectorAguero/loadable_buttons
issue_tracker: https://github.com/hectorAguero/loadable_buttons/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_linter: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

screenshots:
  - description: 'Loadable_buttons gif'
    path: screenshots/preview.gif